# @format

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - VITE_API_URL=http://server:5000
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://joy:xdfrtgyvhfxaszz6424s@cluster0.wj6ps.mongodb.net/expenses?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=xgfdftrcy65uylhgjuhio7fywqdkuqwdqwh8p9ddbhjwduwidqwhduqiwdliuqwdwgbdkwiduy982q6ev2iqhdluaid09ajnywdp89h7w9pdnqwp98ndqww90dwq89dunwq
