# @format

services:
  # Frontend Web Service
  - type: web
    name: finance-manager-client
    env: static
    buildCommand: cd client && npm install && npm build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: finance-manager-api
          type: web
          property: url

  # Backend API Service
  - type: web
    name: finance-manager-api
    env: node
    region: frankfurt
    buildCommand: cd server && npm install
    startCommand: cd server && node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health

